language: node_js
node_js:
- node
before_script:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run build
after_success:
  - codecov
cache: npm
deploy:
  provider: npm
  email: kousha.talebian@gmail.com
  on:
    tags: true
    repo: ktalebian/switch
